# Apps options
$t = kitty fish -c
$f = [float; size (monitor_w*0.85) (monitor_h*0.75)]

# NOTE: if you want to change these config make sure to change it in ~/.config/hypr/_config.sh as well
$s = ~/.config/hypr/scripts
$screenshot_output = -o ~/Pictures/Screenshots/ -f "Screenshot $(date '+%Y-%m-%d %H%M%S').png"
$cursor_theme = Remus-White
$cursor_size = 24

# Default Apps
$browser = helium-browser
$term    = kitty
$editor  = $t nvim
$file    = $t yazi
$fileAlt = nautilus -w

# Rofi
$drun  = pkill rofi || true && rofi -show drun -show-icons
$run   = pkill rofi || true && rofi -show run
$emoji = pkill rofi || true && rofi -show emoji
$clip  = pkill rofi || true && cliphist list | eval rofi -dmenu -display-columns 2 -p "clipboard" | cliphist decode | wl-copy
