source = ./_config.conf
source = ./colors.conf
source = ./configs/env.conf
source = ./configs/autostart.conf
source = ./configs/monitors.conf
source = ./configs/input.conf
source = ./configs/binds.conf
source = ./configs/general.conf
source = ./configs/rules.conf
