source = ./colors.conf

$mono = CaskaydiaCove Nerd Font
$serif = PT Serif, Noto Serif Thai

general {
  hide_cursor = true
  ignore_empty_input = true
  fail_timeout = 1000
}

background {
  path = ~/.cache/wallpaper
  blur_size = 3
  blur_passes = 1
  brightness = 0.5
}

# Password input field
input-field {
  size = 20%, 5%
  outline_thickness = 1

  color = $foreground
  inner_color = rgba($background_hex80)
  outer_color = rgba($foreground_hex80)
  check_color = $warning
  fail_color  = $error

  font_family = $mono
  font_color  = $foreground

  fade_on_empty = true
  rounding = 25

  position = 0, 100
  halign = center
  valign = bottom
}

# Hours
label {
  text = cmd[update:1000] date "+%H"

  color = $foreground
  font_size = 180
  font_family = $serif

  shadow_passes = 2
  shadow_size = 6
  shadow_color = rgba($background_hex80)

  position = 0, 140
  halign = center
  valign = center
}

# Minutes
label {
  text = cmd[update:1000] date "+%M"

  color = $foreground
  font_size = 180
  font_family = $serif

  shadow_passes = 2
  shadow_size = 6
  shadow_color = rgba($background_hex80)

  position = 0, -60
  halign = center
  valign = center
}

# Mpris
label {
  text = cmd[update:1000] echo "𐙚⁺˖ ⸝⸝ $(playerctl -p spotify metadata --format "\{\{ artist }} - \{\{ title }}") ⁺໒꒱ིྀ༝."

  color = $foreground
  font_size = 18
  font_family = $serif

  shadow_passes = 2
  shadow_size = 6
  shadow_color = rgba($background_hex80)

  position = 0, 150
  halign = center
  valign = bottom
}
