source = ./hyprland.conf

general {
  hide_cursor = true
  ignore_empty_input = true
  fail_timeout = 1000
}

background {
  monitor =
  path = ~/.config/hypr/wal
  blur_passes = 2
}

animations {
  enabled = false
}

input-field {
  monitor =
  size = 80%, 5%
  dots_size = 0.5
  dots_spacing = 0.5
  outline_thickness = 1

  inner_color = rgba(00000000)
  outer_color = rgba(00000000)
  check_color = rgba(00000000)
  fail_color = rgba(fb4a37ff)

  font_family = $font
  font_color = rgb(a79883)
  fade_on_empty = true
  rounding = 0

  position = 0, 0
  halign = center
  valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%H:%M')"
    color = rgba(a7988380)
    font_family = $font
    font_size = 48

    position = -10, 0
    halign = right
    valign = bottom
}
