source = ./hyprland.conf

general {
  hide_cursor = true
  ignore_empty_input = true
  fail_timeout = 1000
}

background {
  monitor =
  path = ~/.config/hypr/wal
  brightness = 0.75
  blur_passes = 2
  blur_size = 1
}

input-field {
  monitor =
  size = 20%, 5%
  dots_size = 0.3
  dots_spacing = 0.5
  outline_thickness = 1

  inner_color = rgba(28282880)
  outer_color = rgba(00000000)
  check_color = rgba(fabc33ff)
  fail_color = rgba(fb4a37ff)

  font_family = $font
  font_color = rgb(fbf1c6)
  fade_on_empty = true
  rounding = 100

  shadow_passes = 2
  shadow_size = 10

  position = 0, 20
  halign = center
  valign = bottom
}

label {
  monitor =
  text = cmd[update:10000000000000] echo ' locked'
  color = rgb(a79883)
  font_family = $font bold
  font_size = 14

  shadow_passes = 3
  shadow_size = 25

  position = 0, -155
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo -e "$(date '+%H')"
  color = rgb(fbf1c6)
  font_family = $font bold
  font_size = 128

  shadow_passes = 3
  shadow_size = 25

  position = 0, 70
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo -e "$(date '+%M')"
  color = rgb(fbf1c6)
  font_family = $font bold
  font_size = 128

  shadow_passes = 3
  shadow_size = 25

  position = 0, -70
  halign = center
  valign = center
}
