# apps
$term    = foot
$fterm   = [float; pin on; move (monitor_w*0.25) 50; size (monitor_w*0.5) (monitor_h*0.15)] $term
$file    = $term yazi
$browser = helium-browser

# rofi
$drun = pkill rofi || true && rofi -show drun
$run  = pkill rofi || true && rofi -show run
$clip = pkill rofi || true && cliphist list | eval rofi -dmenu -display-columns 2 -p "clipboard" | cliphist decode | wl-copy

# hypr*
$screenshot_output = -o ~/Pictures/Screenshots/ -f "$(date '+%Y-%m-%d %H-%M-%S').png"
$shutdown = command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit

# scripts
$s   = ~/.config/hypr/scripts
$osd = $s/osd.sh

# window rules
$f = [float; size (monitor_w*0.80) (monitor_h*0.75)]

# font
$font = CaskaydiaCoveNerdFont
$cursor = Adwaita 12
