general {
  gaps_in = 5
  gaps_out = 10

  border_size = 0
  col.active_border = rgba(eadab1ff)
  col.inactive_border = rgba(918273ff)

  allow_tearing = false
}

decoration {
  rounding = 0
  rounding_power = 2

  active_opacity = 0.93
  inactive_opacity = 0.75

  shadow {
    enabled = true
    range = 14
    render_power = 4
    color = rgba(1a1a1a80)
  }

  blur {
    enabled = true
    size = 2
    passes = 3

    vibrancy = 0.1696
  }
}

group {
  groupbar {
    font_size = 14
    font_weight_active = bold

    rounding = 0

    text_color = rgba(eadab1ff)
    text_color_inactive = rgba(665c55ff)
    text_color_locked_active = rgba(fabc33ff)
    text_color_locked_inactive = rgba(665c55ff)

    col.active = rgba(eadab1ff)
    col.inactive = rgba(665c55ff)
    col.locked_active = rgba(fabc33ff)
    col.locked_inactive = rgba(665c55ff)
  }
}

animations {
  enabled = true
  #        NAME              X0    Y0    X1 Y1
  bezier = linear,            0,    0,    0, 1
  bezier = easeInExpo,     0.7,     0, 0.84, 0
  bezier = easeOutExpo,    0.16,    1,  0.3, 1
  bezier = easeOutCirc,       0, 0.55, 0.45, 1
  bezier = easeInOutQuart, 0.76,    0, 0.24, 1

  animation = windows,      1, 3, easeOutExpo, popin
  animation = windowsOut,   1, 3, easeOutExpo, popin 10%
  animation = windowsMove,  1, 3, easeOutExpo, slide
  animation = workspaces,   1, 3, easeOutExpo, slidevert
  animation = fade,         1, 2, easeOutCirc
  animation = fadeLayers,   1, 3, easeInOutQuart
  animation = layers,       1, 3, easeOutExpo, popin 30%
  animation = zoomFactor,   1, 5, easeOutExpo
  animation = monitorAdded, 1, 5, easeOutExpo
}

cursor {
  inactive_timeout = 1
  hide_on_key_press = true
  zoom_detached_camera = false
}

misc {
  font_family = $font
  animate_manual_resizes = true
  animate_mouse_windowdragging = true
}
