exec-once = hyprctl setcursor $cursor
exec-once = pgrep hyprpaper || hyprpaper&
exec-once = pgrep hypridle  || hypridle&

exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
