exec-once = systemctl --user start hyprpolkitagent

exec-once = hyprctl setcursor $cursor_theme 24

exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = awww-daemon
exec-once = waybar
exec-once = pkill -SIGUSR1 waybar
