general {
  gaps_in = 5
  gaps_out = 15

  border_size = 1

  col.active_border = $outline
  col.inactive_border = $outlinedim

  resize_on_border = false
  allow_tearing = false

  layout = dwindle

  snap {
    enabled = true
  }
}

decoration {
  rounding = 10
  rounding_power = 2

  active_opacity = 0.95
  inactive_opacity = 0.89

  shadow {
    enabled = true
    range = 4
    render_power = 2
    color = rgba(1a1a1a80)
  }

  blur {
    enabled = true
    size = 3
    passes = 1
    vibrancy = 0

    popups = true
  }
}

cursor {
  inactive_timeout = 5
  hide_on_key_press = true
  zoom_disable_aa = true
  zoom_detached_camera = false
}

animations {
  enabled = true

  #        NAME,           X0,   Y0,   X1,   Y1
  bezier = easeOutQuint,   0.23, 1,    0.32, 1
  bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
  bezier = linear,         0,    0,    1,    1
  bezier = almostLinear,   0.5,  0.5,  0.75, 1
  bezier = quick,          0.15, 0,    0.1,  1
  bezier = smoothOut,      0.05, 0.95, 0.1,  1

  #           NAME,          ONOFF, SPEED, CURVE,    [STYLE]
  animation = global,        1,     4,     smoothOut
  animation = windows,       1,     4,     smoothOut
  animation = windowsIn,     1,     4,     smoothOut, popin 80%
  animation = windowsOut,    1,     4,     smoothOut, popin 80%
  animation = fade,          1,     4,     smoothOut
  animation = layers,        1,     4,     smoothOut
  animation = layersIn,      1,     4,     smoothOut, popin 80%
  animation = layersOut,     1,     4,     smoothOut, popin 80%
  animation = fadeLayersIn,  1,     4,     smoothOut
  animation = fadeLayersOut, 1,     4,     smoothOut
  animation = workspaces,    1,     4.25,  smoothOut, slidevert
}

misc {
  force_default_wallpaper = 0
  disable_hyprland_logo = true
  disable_splash_rendering = true

  font_family = CaskaydiaCove Nerd Font 12

  mouse_move_enables_dpms = true
  key_press_enables_dpms = true

  animate_manual_resizes = true
  animate_mouse_windowdragging = true

  enable_swallow = true
  swallow_regex = ^kitty$
}
