input {
  kb_layout = us, th
  kb_variant =
  kb_model =
  kb_options = shift:both_capslock_cancel
  kb_rules =

  repeat_delay = 250
  repeat_rate = 30

  follow_mouse = 1

  natural_scroll = true

  sensitivity = -0.42
  accel_profile = flat

  touchpad {
    natural_scroll = true
  }
}
