general {
  resize_on_border = false
  layout = dwindle
}

dwindle {
  pseudotile = true
  preserve_split = true
}

master {
  new_status = master
}

misc {
  enable_swallow          = true
  swallow_regex           = ^(foot)$
  swallow_exception_regex = ^(wev.*)$
}
