plugin {
  easymotion {
    textsize=30

    textcolor=rgba(eadab1ff)
    bgcolor=rgba(28282880)

    blur=1
    blurA=1.0
    xray=0

    textfont=$font
    textpadding=5

    bordersize=0
    bordercolor=rgba(ffffffff)

    rounding=0

    fullscreen_action=none

    motionkeys=abcdefghijklmnopqrstuvwxyz1234567890
    motionlabels=ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890

    only_special = true
  }
}
