windowrule {
  name = suppress-maximize-events
  match:class = .*

  suppress_event = maximize
}

windowrule {
  name = fix-xwayland-drags
  match:class = ^$
  match:title = ^$
  match:xwayland = true
  match:float = true
  match:fullscreen = false
  match:pin = false

  no_focus = true
}

# Effects
windowrule = no_blur on, no_shadow on, match:class ^vktablet$

# Workspaces
windowrule = workspace 1, match:class ^helium$
windowrule = workspace 8, match:class ^vesktop$
windowrule = workspace 9, match:class ^spotify$
windowrule = workspace 10, match:class ^obsidian$

# Float
windowrule = float on, match:class ^ezame$
windowrule = float on, match:class ^vktablet$
windowrule = float on, match:class ^nwg-look$
windowrule = float on, match:class ^nwg-displays$
windowrule = float on, match:class ^thunar$,         match:title ^Rename(.*)$
windowrule = float on, match:class ^chrome-(.*)$,    match:title ^_crx_(.*)$
windowrule = float on, match:class ^(.*)$,           match:title ^Extract(.*)$
windowrule = float on, match:class ^(.*)$,           match:title ^Compress(.*)$
windowrule = float on, match:class ^(.*)$,           match:title ^Save File(|s)$
windowrule = float on, match:class ^(.*)$,           match:title ^Open File(|s)$
windowrule = float on, match:class ^(.*)$,           match:title ^File Operation Progress(.*)$

# No transparent
windowrule = opacity 1.0 override, match:class ^imv$
windowrule = opacity 1.0 override, match:class ^mpv$
windowrule = opacity 1.0 override, match:class ^scrcpy$
windowrule = opacity 1.0 override, match:class ^helium$, match:title ^(.*)Immich(.*)$
windowrule = opacity 1.0 override, match:class ^helium$, match:title ^(.*)(Y|y)ou(T|t)ube(.*)$

windowrule = opacity 1.0 override, match:class ^osu(.)$
windowrule = opacity 1.0 override, match:class ^sober$
windowrule = opacity 1.0 override, match:class ^(.*)(Sober)$
windowrule = opacity 1.0 override, match:class ^(.*)(M|m)inecraft(.*)$

# Layer blur
layerrule = ignore_alpha 0, blur on, match:namespace rofi
layerrule = ignore_alpha 0, blur on, match:namespace menu
layerrule = ignore_alpha 0, blur on, match:namespace waybar
layerrule = ignore_alpha 0, blur on, match:namespace notifications

layerrule = animation slide top, match:namespace notifications

layerrule = animation fade, match:namespace hyprpaper
layerrule = animation fade, match:namespace hyprpicker
layerrule = animation fade, match:namespace selection

